CREATE TABLE SUBSCRIBER
(
    ID      SERIAL PRIMARY KEY,
    NAME    VARCHAR(100) NOT NULL,
    ADDRESS TEXT
);

CREATE TABLE PHONE_NUMBER
(
    NUMBER CHAR(12) PRIMARY KEY,
    SUBSCRIBER INT NOT NULL,
    FOREIGN KEY (SUBSCRIBER) REFERENCES SUBSCRIBER (ID) ON DELETE CASCADE
);

CREATE TABLE CREDIT_TOKEN
(
    ID         SERIAL PRIMARY KEY,
    TOKEN_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE SUBSCRIBER_CREDIT_TOKEN
(
    SUBSCRIBER_ID INT,
    TOKEN_ID      INT,
    PRIMARY KEY (SUBSCRIBER_ID, TOKEN_ID),
    FOREIGN KEY (SUBSCRIBER_ID) REFERENCES SUBSCRIBER (ID) ON DELETE CASCADE,
    FOREIGN KEY (TOKEN_ID) REFERENCES CREDIT_TOKEN (ID) ON DELETE CASCADE
);

CREATE TABLE DIALING_CODE
(
    COUNTRY_CODE CHAR(3) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PAYPHONE
(
    ID       SERIAL PRIMARY KEY,
    LOCATION VARCHAR(255) NOT NULL
);

CREATE TABLE CALL
(
    ID            SERIAL PRIMARY KEY,
    FROM_NUMBER   CHAR(12) NOT NULL,
    TO_NUMBER     CHAR(12) NOT NULL,
    DIALING_CODE  CHAR(3)  NOT NULL,
    PAYPHONE      INT      NULL,
    TOKEN         INT      NULL,
    CALL_DURATION INT      NOT NULL,
    FOREIGN KEY (DIALING_CODE) REFERENCES DIALING_CODE (COUNTRY_CODE),
    FOREIGN KEY (PAYPHONE) REFERENCES PAYPHONE (ID),
    FOREIGN KEY (TOKEN) REFERENCES CREDIT_TOKEN (ID)
);